#!/usr/bin/env node
require('babel-register')();

const conf = require('node-env-conf');

conf.init({ env: 'CONFIG' });

const server = require('./server').default;
const clusterProcess = require('./cluster').default;

if (conf.get('cluster')) {
  clusterProcess(startServer);
} else {
  startServer();
}

function startServer() {
  server.set('port', process.env.PORT || 8080);

  server.listen(server.get('port'), () => {
    console.log(`Express server listening on port ${server.get('port')}`);
  });
}
