// example
export const FETCH_EXAMPLE_MESSAGE = 'FETCH_EXAMPLE_MESSAGE';
export const FETCH_EXAMPLE_MESSAGE_ERROR = 'FETCH_EXAMPLE_MESSAGE_ERROR';
export const UPDATE_EXAMPLE_MESSAGE = 'UPDATE_EXAMPLE_MESSAGE';
